# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cama', models.CharField(max_length=2)),
                ('historia_clinica', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Devuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=60)),
                ('dosis', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mL', 'mL'), ('%', '%'), ('L', 'L')], max_length=5, null=True)),
                ('unidad', models.CharField(choices=[('TABLETA', 'TABLETA'), ('FRASCO', 'FRASCO'), ('AMPULA', 'AMPULA'), ('BULBO', 'BULBO'), ('TUBO', 'TUBO'), ('CREMA', 'CREMA'), ('UNGUENTO', 'UNGUENTO'), ('BOLSA', 'BOLSA'), ('LATA', 'LATA'), ('CAJA', 'CAJA'), ('JALEA', 'JALEA'), ('JERINGA', 'JERINGA'), ('SOBRE', 'SOBRE'), ('OVULO', 'OVULO'), ('UNIDAD', 'UNIDAD'), ('PAQUETE', 'PAQUETE'), ('SUPOSITORIO', 'SUPOSITORIO'), ('VIAL', 'VIAL'), ('COLIRIO', 'COLIRIO'), ('CAPSULA', 'CAPSULA')], max_length=15)),
                ('cantidad_devuelta', models.IntegerField()),
                ('cantidad_confirmada', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('importe', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DevueltoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=40)),
                ('devuelta_por', models.CharField(max_length=40)),
                ('recibida_por', models.CharField(max_length=40)),
                ('num_dev', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=60)),
                ('unidad', models.CharField(blank=True, choices=[('TABLETA', 'TABLETA'), ('FRASCO', 'FRASCO'), ('AMPULA', 'AMPULA'), ('BULBO', 'BULBO'), ('TUBO', 'TUBO'), ('CREMA', 'CREMA'), ('UNGUENTO', 'UNGUENTO'), ('BOLSA', 'BOLSA'), ('LATA', 'LATA'), ('CAJA', 'CAJA'), ('JALEA', 'JALEA'), ('JERINGA', 'JERINGA'), ('SOBRE', 'SOBRE'), ('OVULO', 'OVULO'), ('UNIDAD', 'UNIDAD'), ('PAQUETE', 'PAQUETE'), ('SUPOSITORIO', 'SUPOSITORIO'), ('VIAL', 'VIAL'), ('COLIRIO', 'COLIRIO'), ('CAPSULA', 'CAPSULA')], max_length=15, null=True)),
                ('cantidad', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('codigoex', models.IntegerField(blank=True, null=True)),
                ('precio', models.FloatField(default=0)),
                ('porciento', models.IntegerField(blank=True, null=True)),
                ('todo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_clinica', models.IntegerField()),
                ('producto', models.CharField(max_length=60)),
                ('dosis', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mL', 'mL'), ('%', '%'), ('L', 'L')], max_length=5)),
                ('unidad', models.CharField(choices=[('TABLETA', 'TABLETA'), ('FRASCO', 'FRASCO'), ('AMPULA', 'AMPULA'), ('BULBO', 'BULBO'), ('TUBO', 'TUBO'), ('CREMA', 'CREMA'), ('UNGUENTO', 'UNGUENTO'), ('BOLSA', 'BOLSA'), ('LATA', 'LATA'), ('CAJA', 'CAJA'), ('JALEA', 'JALEA'), ('JERINGA', 'JERINGA'), ('SOBRE', 'SOBRE'), ('OVULO', 'OVULO'), ('UNIDAD', 'UNIDAD'), ('PAQUETE', 'PAQUETE'), ('SUPOSITORIO', 'SUPOSITORIO'), ('VIAL', 'VIAL'), ('COLIRIO', 'COLIRIO'), ('CAPSULA', 'CAPSULA')], max_length=15)),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('codigoex', models.IntegerField(blank=True, null=True)),
                ('precio', models.FloatField(default=0)),
                ('cantidad_solicitada', models.IntegerField()),
                ('medico', models.CharField(max_length=40)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Cama')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.IntegerField()),
                ('importe', models.FloatField(default=0)),
                ('solicitado_por', models.CharField(max_length=40)),
                ('despachado_por', models.CharField(blank=True, max_length=40, null=True)),
                ('recibido_por', models.CharField(max_length=40)),
                ('num_ped', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sala'),
        ),
        migrations.AddField(
            model_name='cama',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sala'),
        ),
    ]
