# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sistema.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cama', models.IntegerField()),
                ('historia_clinica', models.CharField(max_length=11, unique=True, validators=[sistema.models.validar])),
                ('nombre', models.CharField(max_length=30)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(max_length=30)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['num_cama'],
            },
        ),
        migrations.CreateModel(
            name='DevueltoAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado_por', models.CharField(max_length=40)),
                ('recibido_por', models.CharField(max_length=40)),
                ('autorizado_por', models.CharField(max_length=40)),
                ('importe_enviada_total', models.FloatField(default=0)),
                ('importe_recibida_total', models.FloatField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevueltoAlmacenDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(blank=True, null=True)),
                ('importe_enviada', models.FloatField(default=0)),
                ('importe_recibida', models.FloatField(default=0)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('devuelto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devuelto_almacen', to='sistema.DevueltoAlmacen')),
            ],
        ),
        migrations.CreateModel(
            name='DevueltoCama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('medico', models.CharField(max_length=40)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Cama')),
            ],
        ),
        migrations.CreateModel(
            name='DevueltoFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.PositiveIntegerField()),
                ('devuelto_almacen_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.DevueltoAlmacenDetalle')),
            ],
            options={
                'ordering': ['producto'],
            },
        ),
        migrations.CreateModel(
            name='DevueltoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devuelta_por', models.CharField(max_length=40)),
                ('recibida_por', models.CharField(max_length=40)),
                ('aprobado_por', models.CharField(max_length=40)),
                ('despachado_por', models.CharField(max_length=40)),
                ('importe_total', models.FloatField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevueltoSalaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('cantidad_confirmada', models.PositiveIntegerField(blank=True, null=True)),
                ('importe', models.FloatField(default=0)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('devuelto_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devuelto_sala', to='sistema.DevueltoSala')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porciento', models.IntegerField(blank=True, null=True)),
                ('todo', models.PositiveIntegerField()),
                ('fondo_fijo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PedidoAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado_por', models.CharField(max_length=40)),
                ('recibido_por', models.CharField(max_length=40)),
                ('autorizado_por', models.CharField(max_length=40)),
                ('importe_enviada_total', models.FloatField(default=0)),
                ('importe_recibida_total', models.FloatField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAlmacenDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.IntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(blank=True, null=True)),
                ('importe_enviada', models.FloatField(default=0)),
                ('importe_recibida', models.FloatField(default=0)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('pedido_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_almacen', to='sistema.PedidoAlmacen')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('medico', models.CharField(max_length=40)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Cama')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_por', models.CharField(max_length=40)),
                ('despachado_por', models.CharField(max_length=40)),
                ('recibido_por', models.CharField(max_length=40)),
                ('aprobado_por', models.CharField(max_length=40)),
                ('importe_total', models.FloatField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSalaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_entregada', models.PositiveIntegerField(blank=True, null=True)),
                ('importe', models.FloatField(default=0)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('pedido_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_sala', to='sistema.PedidoSala')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to=settings.AUTH_USER_MODEL)),
                ('contabilidad', models.ManyToManyField(blank=True, related_name='contabilidad', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ManyToManyField(blank=True, related_name='farmacia', to=settings.AUTH_USER_MODEL)),
                ('jefe_contabilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe_contabilidad', to=settings.AUTH_USER_MODEL)),
                ('jefe_farmacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe_farmacia', to=settings.AUTH_USER_MODEL)),
                ('secretaria_sala', models.ManyToManyField(blank=True, related_name='secretaria_sala', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('dosis', models.FloatField()),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[sistema.models.validar])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Presentacion')),
            ],
            options={
                'ordering': ['unidad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=40)),
                ('apodo', models.CharField(max_length=20)),
                ('centro_costo', models.CharField(max_length=3, unique=True, validators=[sistema.models.validar])),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['centro_costo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='pedidosaladetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sala'),
        ),
        migrations.AddField(
            model_name='pedidocama',
            name='pedido_sala_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.PedidoSalaDetalle'),
        ),
        migrations.AddField(
            model_name='pedidocama',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='pedidoalmacendetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='existencia', to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='devueltosaladetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='devueltosala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sala'),
        ),
        migrations.AddField(
            model_name='devueltofarmacia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='devueltocama',
            name='devuelto_sala_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.DevueltoSalaDetalle'),
        ),
        migrations.AddField(
            model_name='devueltocama',
            name='justificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Justificacion'),
        ),
        migrations.AddField(
            model_name='devueltocama',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='devueltoalmacendetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='cama',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sala'),
        ),
    ]
