# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0002_remove_existencia_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='unidad',
            field=models.CharField(blank=True, choices=[('TABLETA', 'TABLETA'), ('FRASCO', 'FRASCO'), ('AMPULA', 'AMPULA'), ('BULBO', 'BULBO'), ('TUBO', 'TUBO'), ('CREMA', 'CREMA'), ('UNGUENTO', 'UNGUENTO'), ('BOLSA', 'BOLSA'), ('LATA', 'LATA'), ('CAJA', 'CAJA'), ('JALEA', 'JALEA'), ('JERINGA', 'JERINGA'), ('SOBRE', 'SOBRE'), ('OVULO', 'OVULO'), ('UNIDAD', 'UNIDAD'), ('PAQUETE', 'PAQUETE'), ('SUPOSITORIO', 'SUPOSITORIO'), ('VIAL', 'VIAL'), ('COLIRIO', 'COLIRIO'), ('CAPSULA', 'CAPSULA')], max_length=15, null=True),
        ),
    ]
