# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0004_remove_pedidocama_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocama',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
