# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0005_pedidocama_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocama',
            name='exist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.Existencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devuelto',
            name='unidad_medida',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mL', 'mL'), ('%', '%'), ('L', 'L')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existencia',
            name='codigo',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existencia',
            name='unidad',
            field=models.CharField(choices=[('TABLETA', 'TABLETA'), ('FRASCO', 'FRASCO'), ('AMPULA', 'AMPULA'), ('BULBO', 'BULBO'), ('TUBO', 'TUBO'), ('CREMA', 'CREMA'), ('UNGUENTO', 'UNGUENTO'), ('BOLSA', 'BOLSA'), ('LATA', 'LATA'), ('CAJA', 'CAJA'), ('JALEA', 'JALEA'), ('JERINGA', 'JERINGA'), ('SOBRE', 'SOBRE'), ('OVULO', 'OVULO'), ('UNIDAD', 'UNIDAD'), ('PAQUETE', 'PAQUETE'), ('SUPOSITORIO', 'SUPOSITORIO'), ('VIAL', 'VIAL'), ('COLIRIO', 'COLIRIO'), ('CAPSULA', 'CAPSULA')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidocama',
            name='codigo',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidosala',
            name='despachado_por',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
