# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20180124_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('unidad', models.CharField(choices=[('TABLETA', 'TABLETA'), ('FRASCO', 'FRASCO'), ('AMPULA', 'AMPULA'), ('BULBO', 'BULBO'), ('TUBO', 'TUBO'), ('CREMA', 'CREMA'), ('UNGUENTO', 'UNGUENTO'), ('BOLSA', 'BOLSA'), ('LATA', 'LATA'), ('CAJA', 'CAJA'), ('JALEA', 'JALEA'), ('JERINGA', 'JERINGA'), ('SOBRE', 'SOBRE'), ('OVULO', 'OVULO'), ('UNIDAD', 'UNIDAD'), ('PAQUETE', 'PAQUETE'), ('SUPOSITORIO', 'SUPOSITORIO'), ('VIAL', 'VIAL'), ('COLIRIO', 'COLIRIO'), ('CAPSULA', 'CAPSULA')], max_length=15)),
                ('codigo', models.CharField(max_length=15)),
                ('codigoex', models.IntegerField(blank=True, null=True)),
                ('precio', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='codigoex',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='codigoex',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='exist',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='pedidocama',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='producto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
            preserve_default=False,
        ),
    ]
