# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20180124_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocama',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
    ]
