# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20180125_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devuelto',
            name='cantidad_confirmada',
        ),
        migrations.RemoveField(
            model_name='devuelto',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='devuelto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='devuelto',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='historia_clinica',
        ),
        migrations.AddField(
            model_name='devueltosala',
            name='cantidad_confirmada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devueltosala',
            name='importe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devuelto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
        migrations.AlterField(
            model_name='devueltosala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sala'),
        ),
    ]
