# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20180126_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuelto',
            name='cama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Cama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devuelto',
            name='medico',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
