# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-01 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20180131_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='devuelto',
            name='historia_clinica',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidocama',
            name='historia_clinica',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devuelto',
            name='justificacion',
            field=models.CharField(choices=[('Fallecimiento', 'Fallecimiento'), ('Dado de alta', 'Dado de alta'), ('Otra', 'Otra'), ('Cambio de tratamiento', 'Cambio de tratamiento'), ('Traslado', 'Traslado')], max_length=40),
        ),
    ]
