# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20180123_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevueltoFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('justificacion', models.CharField(choices=[('VENCIMIENTO', 'VENCIMIENTO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('RETENIDO', 'RETENIDO'), ('MAL ESTADO', 'MAL ESTADO')], max_length=40)),
                ('num_dev', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('num_ped', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='tarjetaestiba',
            old_name='entrada',
            new_name='entrada_ped',
        ),
        migrations.RenameField(
            model_name='tarjetaestiba',
            old_name='salida',
            new_name='salida_dev',
        ),
        migrations.AddField(
            model_name='devueltocama',
            name='num_dev',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidocama',
            name='num_ped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjetaestiba',
            name='saldo',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('OTRA', 'OTRA'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO')], max_length=40),
        ),
        migrations.AddField(
            model_name='pedidofarmacia',
            name='tarjeta_estiba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.TarjetaEstiba'),
        ),
        migrations.AddField(
            model_name='devueltofarmacia',
            name='tarjeta_estiba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.TarjetaEstiba'),
        ),
    ]
