# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20180124_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('EGRESO', 'EGRESO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('MAL ESTADO', 'MAL ESTADO'), ('RETENIDO', 'RETENIDO')], max_length=40),
        ),
    ]
