# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_auto_20180124_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='ususario',
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('TRASLADO', 'TRASLADO'), ('EGRESO', 'EGRESO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('RETENIDO', 'RETENIDO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('MAL ESTADO', 'MAL ESTADO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
