# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0022_auto_20180124_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO'), ('OTRA', 'OTRA'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO')], max_length=40),
        ),
    ]
