# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_auto_20180124_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devueltofarmacia',
            name='num_dev',
        ),
        migrations.RemoveField(
            model_name='devueltosala',
            name='num_dev',
        ),
        migrations.RemoveField(
            model_name='pedidosala',
            name='num_ped',
        ),
        migrations.RemoveField(
            model_name='tarjetaestiba',
            name='num_ped',
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('EGRESO', 'EGRESO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('RETENIDO', 'RETENIDO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('MAL ESTADO', 'MAL ESTADO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO')], max_length=40),
        ),
    ]
