# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0027_auto_20180124_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevueltoSalaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('cantidad_confirmada', models.IntegerField()),
                ('importe', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='devueltosala',
            name='cantidad_confirmada',
        ),
        migrations.RemoveField(
            model_name='devueltosala',
            name='importe',
        ),
        migrations.AlterField(
            model_name='cama',
            name='num_cama',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('EGRESO', 'EGRESO'), ('OTRA', 'OTRA'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO'), ('FALLECIMIENTO', 'FALLECIMIENTO')], max_length=40),
        ),
        migrations.AddField(
            model_name='devueltosaladetalle',
            name='devuelto_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.DevueltoSala'),
        ),
        migrations.AddField(
            model_name='devueltosaladetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.Producto'),
        ),
        migrations.AddField(
            model_name='devueltocama',
            name='devuelto_sala_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.DevueltoSalaDetalle'),
        ),
    ]
