# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0030_auto_20180125_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='devueltosaladetalle',
            name='saldo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pedidosaladetalle',
            name='saldo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('EGRESO', 'EGRESO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('MAL ESTADO', 'MAL ESTADO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('RETENIDO', 'RETENIDO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tarjetaestiba',
            name='saldo',
            field=models.FloatField(default=0),
        ),
    ]
