# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0031_auto_20180126_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devueltosaladetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedidosaladetalle',
            name='producto',
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('EGRESO', 'EGRESO'), ('OTRA', 'OTRA'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('TRASLADO', 'TRASLADO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('RETENIDO', 'RETENIDO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('MAL ESTADO', 'MAL ESTADO')], max_length=40),
        ),
    ]
