# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0035_auto_20180127_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetaestiba',
            name='saldo',
        ),
        migrations.AddField(
            model_name='tarjetaestibadetalle',
            name='tarjeta_estiba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.TarjetaEstiba'),
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('EGRESO', 'EGRESO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('VENCIMIENTO', 'VENCIMIENTO'), ('RETENIDO', 'RETENIDO'), ('MAL ESTADO', 'MAL ESTADO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO')], max_length=40),
        ),
    ]
