# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0036_auto_20180127_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('OTRA', 'OTRA'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('EGRESO', 'EGRESO'), ('TRASLADO', 'TRASLADO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('VENCIMIENTO', 'VENCIMIENTO'), ('MAL ESTADO', 'MAL ESTADO'), ('RETENIDO', 'RETENIDO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO')], max_length=40),
        ),
    ]
