# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0039_auto_20180127_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetaestiba',
            name='unidad',
            field=models.CharField(choices=[('TABLETA', 'TABLETA'), ('FRASCO', 'FRASCO'), ('AMPULA', 'AMPULA'), ('BULBO', 'BULBO'), ('TUBO', 'TUBO'), ('CREMA', 'CREMA'), ('UNGUENTO', 'UNGUENTO'), ('BOLSA', 'BOLSA'), ('LATA', 'LATA'), ('CAJA', 'CAJA'), ('JALEA', 'JALEA'), ('JERINGA', 'JERINGA'), ('SOBRE', 'SOBRE'), ('OVULO', 'OVULO'), ('UNIDAD', 'UNIDAD'), ('PAQUETE', 'PAQUETE'), ('SUPOSITORIO', 'SUPOSITORIO'), ('VIAL', 'VIAL'), ('COLIRIO', 'COLIRIO'), ('CAPSULA', 'CAPSULA')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO'), ('OTRA', 'OTRA')], max_length=40),
        ),
    ]
