# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0040_auto_20180127_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('EGRESO', 'EGRESO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('OTRA', 'OTRA'), ('TRASLADO', 'TRASLADO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('MAL ESTADO', 'MAL ESTADO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('RETENIDO', 'RETENIDO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tarjetaestiba',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
