# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0043_auto_20180128_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaladetalle',
            name='dosis',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidosaladetalle',
            name='unidad_medida',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mL', 'mL'), ('%', '%'), ('L', 'L')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('OTRA', 'OTRA'), ('TRASLADO', 'TRASLADO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('MAL ESTADO', 'MAL ESTADO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('RETENIDO', 'RETENIDO')], max_length=40),
        ),
    ]
