# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0045_auto_20180123_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosaladetalle',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='pedidosaladetalle',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='devueltocama',
            name='unidad',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidocama',
            name='unidad',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='dosis',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mL', 'mL'), ('%', '%'), ('L', 'L')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='unidad_medida',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='devueltosaladetalle',
            name='devuelto_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devuelto_sala', to='sistema.DevueltoSala'),
        ),
        migrations.AlterField(
            model_name='pedidocama',
            name='unidad_medida',
            field=models.CharField(max_length=5),
        ),
    ]
