# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0048_auto_20180125_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='devueltosala',
            name='aprobado_por',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='aprobado_por',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('EGRESO', 'EGRESO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO'), ('OTRA', 'OTRA')], max_length=40),
        ),
    ]
