# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0051_auto_20180125_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltosaladetalle',
            name='cantidad_confirmada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
