# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0053_auto_20180125_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(max_length=40),
        ),
    ]
