# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0054_auto_20180125_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='devueltosala',
            name='despachado_por',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
