# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0056_auto_20180124_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='secretaria',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
