# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0058_pedidosaladetalle_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='devueltosaladetalle',
            name='existencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Existencia'),
            preserve_default=False,
        ),
    ]
