# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0059_devueltosaladetalle_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='devueltosala',
            name='importe_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pedidosala',
            name='importe_total',
            field=models.FloatField(default=0),
        ),
    ]
