# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0060_auto_20180320_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltosaladetalle',
            name='saldo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidosaladetalle',
            name='saldo',
            field=models.IntegerField(),
        ),
    ]
