# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0061_auto_20180320_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devueltosaladetalle',
            name='existencia',
        ),
        migrations.RemoveField(
            model_name='pedidosaladetalle',
            name='existencia',
        ),
    ]
