# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0062_auto_20180321_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=8),
        ),
    ]
