# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0063_auto_20180323_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cama',
            options={'ordering': ['num_cama']},
        ),
        migrations.AlterModelOptions(
            name='existencia',
            options={'ordering': ['producto']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['unidad', 'nombre']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='devueltocama',
            order_with_respect_to='cama',
        ),
        migrations.AlterOrderWithRespectTo(
            name='devueltosaladetalle',
            order_with_respect_to='producto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='pedidocama',
            order_with_respect_to='cama',
        ),
        migrations.AlterOrderWithRespectTo(
            name='pedidosaladetalle',
            order_with_respect_to='producto',
        ),
    ]
