# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0067_auto_20180323_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='fondo_fijo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
