# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-24 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0069_auto_20180323_1400'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='devueltosaladetalle',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='pedidosaladetalle',
            order_with_respect_to=None,
        ),
    ]
