# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0071_auto_20180326_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
