# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-29 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0074_auto_20180327_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.IntegerField(max_length=11),
        ),
    ]
