# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-17 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0079_cama_fecha_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoFarmaciaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=60)),
                ('unidad', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
    ]
