# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0080_pedidofarmaciadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaCoberturaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=60)),
                ('unidad', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['entidad'],
            },
        ),
        migrations.DeleteModel(
            name='PedidoFarmaciaDetalle',
        ),
        migrations.AddField(
            model_name='bajacoberturadetalle',
            name='pedido_farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_farmacia', to='sistema.PedidoFarmacia'),
        ),
    ]
