# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-18 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0081_auto_20180417_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('siglas', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
