# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-24 17:54
from __future__ import unicode_literals

import sistema.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0084_auto_20180422_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, validators=[sistema.models.validar]),
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Justificacion'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, validators=[sistema.models.validar]),
        ),
    ]
