# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-25 16:08
from __future__ import unicode_literals

import Sistema_Gestion_Medicamentos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0085_auto_20180424_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevueltoFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.Producto')),
            ],
            options={
                'ordering': ['producto'],
            },
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
    ]
