# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-25 17:59
from __future__ import unicode_literals

import sistema.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0086_auto_20180425_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevueltoAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado_por', models.CharField(max_length=40)),
                ('recibido_por', models.CharField(max_length=40)),
                ('autorizado_por', models.CharField(max_length=40)),
                ('importe_enviada_total', models.FloatField(default=0)),
                ('importe_recibida_total', models.FloatField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevueltoAlmacenDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(blank=True, null=True)),
                ('importe_enviada', models.FloatField(default=0)),
                ('importe_recibida', models.FloatField(default=0)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('devuelto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devuelto_almacen', to='sistema.DevueltoAlmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto')),
            ],
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, validators=[sistema.models.validar]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, validators=[sistema.models.validar]),
        ),
    ]
