# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-26 18:37
from __future__ import unicode_literals

import Sistema_Gestion_Medicamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0089_auto_20180426_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajacoberturadetalle',
            name='pedido_farmacia',
        ),
        migrations.RemoveField(
            model_name='pedidofarmacia',
            name='pedido_almacen_detalle',
        ),
        migrations.RemoveField(
            model_name='pedidofarmacia',
            name='producto',
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
        migrations.DeleteModel(
            name='BajaCoberturaDetalle',
        ),
        migrations.DeleteModel(
            name='PedidoFarmacia',
        ),
    ]
