# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-12 07:50
from __future__ import unicode_literals

import sistema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0100_auto_20180509_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, unique=True, validators=[sistema.models.validar]),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='fondo_fijo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidocama',
            name='cantidad_solicitada',
            field=models.IntegerField(validators=[sistema.models.validar]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, unique=True, validators=[sistema.models.validar]),
        ),
    ]
