# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-17 03:24
from __future__ import unicode_literals

import sistema.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0110_auto_20180515_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to=settings.AUTH_USER_MODEL)),
                ('contabilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad', to=settings.AUTH_USER_MODEL)),
                ('farmacia_jefe_farmacia', models.ManyToManyField(blank=True, related_name='farmacia_jefe_farmacia', to=settings.AUTH_USER_MODEL)),
                ('jefe_farmacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe_farmacia', to=settings.AUTH_USER_MODEL)),
                ('jefe_farmacia_contabilidad', models.ManyToManyField(blank=True, related_name='jefe_farmacia_contabilidad', to=settings.AUTH_USER_MODEL)),
                ('secretaria_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretaria_sala', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, unique=True, validators=[sistema.models.validar]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, unique=True, validators=[sistema.models.validar]),
        ),
    ]
