# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-03 16:50
from __future__ import unicode_literals

import sistema.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0117_auto_20180517_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apodo', models.CharField(max_length=20)),
                ('centro_costo', models.CharField(max_length=3, unique=True, validators=[sistema.models.validar])),
            ],
            options={
                'ordering': ['centro_costo'],
            },
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={},
        ),
        migrations.RemoveField(
            model_name='sala',
            name='apodo',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='centro_costo',
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, unique=True, validators=[sistema.models.validar]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Servicio'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema.Servicio'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
