# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-06 06:48
from __future__ import unicode_literals

import sistema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0121_auto_20180703_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='farmacia',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='devueltoalmacen',
            name='farmacia',
        ),
        migrations.RemoveField(
            model_name='pedidoalmacen',
            name='farmacia',
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, unique=True, validators=[sistema.models.validar]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, unique=True, validators=[sistema.models.validar]),
        ),
        migrations.DeleteModel(
            name='Farmacia',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
