# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0003_existencia_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocama',
            name='codigo',
        ),
    ]
