# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-01 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0011_devuelto_justificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuelto',
            name='justificacion',
            field=models.CharField(choices=[('Dado de alta', 'Dado de alta'), ('Otra', 'Otra'), ('Traslado', 'Traslado'), ('Fallecimiento', 'Fallecimiento'), ('Cambio de tratamiento', 'Cambio de tratamiento')], max_length=40),
        ),
    ]
