# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0015_auto_20180123_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidofarmacia',
            name='tarjeta_estiba',
        ),
        migrations.AddField(
            model_name='tarjetaestiba',
            name='cantidad_solicitada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjetaestiba',
            name='num_ped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('RETENIDO', 'RETENIDO'), ('MAL ESTADO', 'MAL ESTADO'), ('VENCIMIENTO', 'VENCIMIENTO')], max_length=40),
        ),
        migrations.DeleteModel(
            name='PedidoFarmacia',
        ),
    ]
