# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0023_auto_20180124_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaladetalle',
            name='pedido_sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.PedidoSala'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO'), ('OTRA', 'OTRA'), ('TRASLADO', 'TRASLADO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('MAL ESTADO', 'MAL ESTADO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('RETENIDO', 'RETENIDO')], max_length=40),
        ),
    ]
