# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0026_auto_20180124_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devueltocama',
            name='num_dev',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='num_ped',
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('EGRESO', 'EGRESO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('RETENIDO', 'RETENIDO'), ('MAL ESTADO', 'MAL ESTADO')], max_length=40),
        ),
    ]
