# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0033_auto_20180126_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaEstibaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_ped', models.IntegerField()),
                ('salida_dev', models.IntegerField()),
                ('firma', models.CharField(max_length=40)),
                ('referencia', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('fecha', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='tarjetaestiba',
            old_name='entrada_ped',
            new_name='maximo',
        ),
        migrations.RenameField(
            model_name='tarjetaestiba',
            old_name='salida_dev',
            new_name='minimo',
        ),
        migrations.AddField(
            model_name='tarjetaestiba',
            name='autorizado',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjetaestiba',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjetaestiba',
            name='ubicacion',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjetaestiba',
            name='unidad_medida',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mL', 'mL'), ('%', '%'), ('L', 'L')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('EGRESO', 'EGRESO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('RETENIDO', 'RETENIDO'), ('MAL ESTADO', 'MAL ESTADO')], max_length=40),
        ),
    ]
