# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0034_auto_20180127_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetaestiba',
            name='cantidad_solicitada',
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('TRASLADO', 'TRASLADO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('EGRESO', 'EGRESO'), ('OTRA', 'OTRA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('MAL ESTADO', 'MAL ESTADO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('RETENIDO', 'RETENIDO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO')], max_length=40),
        ),
    ]
