# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0037_auto_20180127_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('OTRA', 'OTRA'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('TRASLADO', 'TRASLADO'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('EGRESO', 'EGRESO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO'), ('RETENIDO', 'RETENIDO'), ('MAL ESTADO', 'MAL ESTADO'), ('VENCIMIENTO', 'VENCIMIENTO')], max_length=40),
        ),
    ]
