# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-28 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0042_auto_20180127_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('FALLECIMIENTO', 'FALLECIMIENTO'), ('OTRA', 'OTRA'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO'), ('EGRESO', 'EGRESO'), ('TRASLADO', 'TRASLADO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='justificacion',
            field=models.CharField(choices=[('RETENIDO', 'RETENIDO'), ('MAL ESTADO', 'MAL ESTADO'), ('VENCIMIENTO', 'VENCIMIENTO'), ('DISMINUCION DEL FONDO FIJO', 'DISMINUCION DEL FONDO FIJO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='devueltosaladetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.Producto'),
        ),
        migrations.AlterField(
            model_name='pedidosaladetalle',
            name='pedido_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_sala', to='Sistema_Gestion_Medicamentos.PedidoSala'),
        ),
        migrations.AlterField(
            model_name='pedidosaladetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Gestion_Medicamentos.Producto'),
        ),
    ]
