# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0046_auto_20180125_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='apodo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='centro_costo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='justificacion',
            field=models.CharField(choices=[('EGRESO', 'EGRESO'), ('OTRA', 'OTRA'), ('FALLECIMIENTO', 'FALLECIMIENTO'), ('TRASLADO', 'TRASLADO'), ('CAMBIO DE TRATAMIENTO', 'CAMBIO DE TRATAMIENTO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
