# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0055_devueltosala_despachado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devueltocama',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='devueltocama',
            name='historia_clinica',
        ),
        migrations.RemoveField(
            model_name='devueltocama',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='devueltocama',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='historia_clinica',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='pedidocama',
            name='unidad_medida',
        ),
    ]
