# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0065_auto_20180323_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-unidad', '-nombre']},
        ),
    ]
