# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-27 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0073_auto_20180326_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existencia',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='devueltocama',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='pedidocama',
            order_with_respect_to=None,
        ),
    ]
