# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-29 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0075_auto_20180329_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.IntegerField(),
        ),
    ]
