# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-15 03:49
from __future__ import unicode_literals

import Sistema_Gestion_Medicamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0105_auto_20180514_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencia',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, unique=True, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='todo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, unique=True, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
    ]
