# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-15 05:57
from __future__ import unicode_literals

import Sistema_Gestion_Medicamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_Medicamentos', '0106_auto_20180514_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='historia_clinica',
            field=models.CharField(max_length=11, unique=True, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
        migrations.AlterField(
            model_name='devueltoalmacendetalle',
            name='cantidad_enviada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='devueltoalmacendetalle',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devueltocama',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='devueltofarmacia',
            name='cantidad_enviada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='devueltosaladetalle',
            name='cantidad_confirmada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devueltosaladetalle',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='fondo_fijo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='todo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidoalmacendetalle',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocama',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidosaladetalle',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosaladetalle',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='centro_costo',
            field=models.CharField(max_length=3, unique=True, validators=[Sistema_Gestion_Medicamentos.models.validar]),
        ),
    ]
